# Generated by Django 3.2.3 on 2021-09-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ardash_piechart',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
