# Generated by Django 3.2.3 on 2021-08-15 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_selections', models.TextField(blank=True, null=True)),
                ('user_selections_last_updated', models.DateTimeField(blank=True, null=True)),
                ('user_selections_created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'USER_SELECTIONS_MODEL',
                'verbose_name_plural': 'USER_SELECTIONS_MODEL',
                'db_table': 'USER_SELECTIONS_MODEL',
            },
        ),
    ]
