# Generated by Django 3.2.3 on 2021-08-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('products', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MAIN_DATA',
                'verbose_name_plural': 'MAIN_DATA',
                'db_table': 'MAIN_DATA',
            },
        ),
    ]
