# Generated by Django 3.2.3 on 2021-08-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_city_maindata_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindata',
            old_name='group',
            new_name='groupname',
        ),
    ]
