# Generated by Django 3.2.3 on 2021-08-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_rename_group_maindata_groupname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindata',
            name='groupname',
        ),
        migrations.AddField(
            model_name='maindata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
