# Generated by Django 3.2.3 on 2021-08-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20210828_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
