# Generated by Django 3.2.3 on 2021-08-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20210828_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindata',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maindata',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
