# Generated by Django 3.2.3 on 2021-08-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20210828_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindata',
            old_name='group',
            new_name='group_name',
        ),
    ]
