# Generated by Django 3.2.3 on 2021-09-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_userbookmarks_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDataAR',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('aging', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MAIN_DATA_AR',
                'verbose_name_plural': 'MAIN_DATA_AR',
                'db_table': 'MAIN_DATA_AR',
            },
        ),
    ]
