# Generated by Django 3.2.3 on 2021-09-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_maindataar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'LEDGER',
                'verbose_name_plural': 'LEDGER',
                'db_table': 'LEDGER',
            },
        ),
    ]
