# Generated by Django 3.2.3 on 2021-09-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_accountsortorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsortorder',
            name='subtotal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
