# Generated by Django 3.2.3 on 2021-09-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_accountsortorder_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsortorder',
            old_name='order',
            new_name='sort_order',
        ),
    ]
