# Generated by Django 3.2.3 on 2021-09-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_rename_order_accountsortorder_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsortorder',
            name='account_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
