# Generated by Django 3.2.3 on 2021-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_accountsortorder_account_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsortorder',
            name='account_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
