# Generated by Django 3.2.3 on 2021-09-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_accountsortorder_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTitles',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'MOVIE_TITLES',
                'verbose_name_plural': 'MOVIE_TITLES',
                'db_table': 'MOVIE_TITLES',
            },
        ),
    ]
