# Generated by Django 3.2.3 on 2021-09-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_movietitles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieTitles',
        ),
    ]
