# Generated by Django 3.2.7 on 2021-09-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_delete_movietitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('movieId', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'MOVIES_MODEL',
                'verbose_name_plural': 'MOVIES_MODEL',
                'db_table': 'MOVIES_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('watch_id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(blank=True, max_length=100, null=True)),
                ('movieId', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'RATINGS_MODEL',
                'verbose_name_plural': 'RATINGS_MODEL',
                'db_table': 'RATINGS_MODEL',
            },
        ),
    ]
